/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123SettingsChar125ManifestDotjsonRouteImport } from './routes/{-$settings}/manifest[.]json'
import { Route as Char123SettingsChar125ConfigureRouteImport } from './routes/{-$settings}/configure'
import { Route as Char123SettingsChar125MetaTypeChar123idChar125DotjsonRouteImport } from './routes/{-$settings}/meta.$type.{$id}[.]json'
import { Route as Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRouteImport } from './routes/{-$settings}/catalog.$type.$catalog.{-$query}[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123SettingsChar125ManifestDotjsonRoute =
  Char123SettingsChar125ManifestDotjsonRouteImport.update({
    id: '/{-$settings}/manifest.json',
    path: '/{-$settings}/manifest.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123SettingsChar125ConfigureRoute =
  Char123SettingsChar125ConfigureRouteImport.update({
    id: '/{-$settings}/configure',
    path: '/{-$settings}/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute =
  Char123SettingsChar125MetaTypeChar123idChar125DotjsonRouteImport.update({
    id: '/{-$settings}/meta/$type/{$id}.json',
    path: '/{-$settings}/meta/$type/{$id}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute =
  Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRouteImport.update(
    {
      id: '/{-$settings}/catalog/$type/$catalog/{-$query}.json',
      path: '/{-$settings}/catalog/$type/$catalog/{-$query}.json',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$settings}/configure': typeof Char123SettingsChar125ConfigureRoute
  '/{-$settings}/manifest.json': typeof Char123SettingsChar125ManifestDotjsonRoute
  '/{-$settings}/meta/$type/{$id}.json': typeof Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute
  '/{-$settings}/catalog/$type/$catalog/{-$query}.json': typeof Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{-$settings}/configure': typeof Char123SettingsChar125ConfigureRoute
  '/{-$settings}/manifest.json': typeof Char123SettingsChar125ManifestDotjsonRoute
  '/{-$settings}/meta/$type/{$id}.json': typeof Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute
  '/{-$settings}/catalog/$type/$catalog/{-$query}.json': typeof Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$settings}/configure': typeof Char123SettingsChar125ConfigureRoute
  '/{-$settings}/manifest.json': typeof Char123SettingsChar125ManifestDotjsonRoute
  '/{-$settings}/meta/$type/{$id}.json': typeof Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute
  '/{-$settings}/catalog/$type/$catalog/{-$query}.json': typeof Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$settings}/configure'
    | '/{-$settings}/manifest.json'
    | '/{-$settings}/meta/$type/{$id}.json'
    | '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$settings}/configure'
    | '/{-$settings}/manifest.json'
    | '/{-$settings}/meta/$type/{$id}.json'
    | '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
  id:
    | '__root__'
    | '/'
    | '/{-$settings}/configure'
    | '/{-$settings}/manifest.json'
    | '/{-$settings}/meta/$type/{$id}.json'
    | '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123SettingsChar125ConfigureRoute: typeof Char123SettingsChar125ConfigureRoute
  Char123SettingsChar125ManifestDotjsonRoute: typeof Char123SettingsChar125ManifestDotjsonRoute
  Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute: typeof Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute
  Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute: typeof Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$settings}/manifest.json': {
      id: '/{-$settings}/manifest.json'
      path: '/{-$settings}/manifest.json'
      fullPath: '/{-$settings}/manifest.json'
      preLoaderRoute: typeof Char123SettingsChar125ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$settings}/configure': {
      id: '/{-$settings}/configure'
      path: '/{-$settings}/configure'
      fullPath: '/{-$settings}/configure'
      preLoaderRoute: typeof Char123SettingsChar125ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$settings}/meta/$type/{$id}.json': {
      id: '/{-$settings}/meta/$type/{$id}.json'
      path: '/{-$settings}/meta/$type/{$id}.json'
      fullPath: '/{-$settings}/meta/$type/{$id}.json'
      preLoaderRoute: typeof Char123SettingsChar125MetaTypeChar123idChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$settings}/catalog/$type/$catalog/{-$query}.json': {
      id: '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
      path: '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
      fullPath: '/{-$settings}/catalog/$type/$catalog/{-$query}.json'
      preLoaderRoute: typeof Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123SettingsChar125ConfigureRoute: Char123SettingsChar125ConfigureRoute,
  Char123SettingsChar125ManifestDotjsonRoute:
    Char123SettingsChar125ManifestDotjsonRoute,
  Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute:
    Char123SettingsChar125MetaTypeChar123idChar125DotjsonRoute,
  Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute:
    Char123SettingsChar125CatalogTypeCatalogChar123QueryChar125DotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
